-- CareerForge's existing SQLite data model, expressed for Supabase PostgreSQL.
-- All feature-specific records remain JSON-serialized in user_records.payload.

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    record_id TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (user_id, category, record_id)
);

CREATE INDEX IF NOT EXISTS idx_user_records_lookup
    ON public.user_records(user_id, category, created_at);

CREATE TABLE IF NOT EXISTS public.rate_limits (
    rate_key TEXT PRIMARY KEY,
    window_start BIGINT NOT NULL,
    request_count BIGINT NOT NULL
);
